version: '3.4'

services:
  db:
    ports:
      - 27017:27017
  sample:
    image: sample:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    env_file: 
      - debug.env
    volumes: 
      - node_cache:/usr/src/app/node_modules
    command: ["npm", "start"]
  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    depends_on:
      - sample
    networks:
      - server
    ports:
      - 4040:4040
    environment:
      - NGROK_PROTOCOL=HTTP
      - NGROK_PORT=sample:8080
      - NGROK_REGION=ap
      - NGROK_DEBUG=true
      - NGROK_BINDTLS=true
volumes:
  node_cache:
  mongo_data:
  mongo_config_db: