version: '3.4'

services:
  db:
    ports:
      - 27017:27017
  sample:
    image: sample:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    env_file: 
      - debug.env
    volumes: 
      - node_cache:/usr/src/app/node_modules    
volumes:
  node_cache:
  mongo_data:
  mongo_config_db: