version: '3.4'

services:
  sample:
    image: sample
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes: 
      - node_cache:/usr/src/app/node_modules
      - .:/usr/src/app
volumes:
  node_cache: